FROM instrumentisto/flutter:3.29.2

ARG ssh_directory=/root/.ssh
ARG github_ssh_file=${ssh_directory}/id_rsa

RUN --mount=type=secret,id=github_private_key \
    cp /run/secrets/github_private_key ${github_ssh_file}
RUN chmod 0400 ${github_ssh_file}

RUN --mount=type=secret,id=github_public_key \
    cp /run/secrets/github_public_key ${github_ssh_file}.pub
RUN chmod 0400 ${github_ssh_file}.pub

RUN echo "StrictHostKeyChecking no" > ${ssh_directory}/config
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts
