#!/bin/sh

if [ "$1" = "-h" -o "$1" = "--help" ]; then
    echo 'Annotation dev setup for kitty terminal'
    echo '  Starts the Annotation Interface, Server and their databases in split windows.'
    echo "  Run from the repository's root."
    echo ''
    echo 'optional arguments:'
    echo '  -h, --help     show this message and exit'
    echo '  -s, --server   run the Annotation Server instead of the Interface (default)'
    echo '                 in the tallest window'
    exit 0
fi

if [ "$TERM" != "xterm-kitty" ]; then
    echo 'Unsupported terminal.'
    exit 1
fi

if  [ ! -d annotation-interface -o ! -d annotation-server ]; then
    echo "Run from the repository's root."
    exit 1
fi


CWD=`pwd`

AS=('cd annotation-server && yarn start:dev' 'cd annotation-server && docker compose up')
AI=('cd annotation-interface && yarn dev' 'cd annotation-interface && docker compose up')

if [ "$1" = "-s" -o "$1" = "--server" ]; then
    MAIN=("${AS[@]}")
    SEC=("${AI[@]}")
else
    MAIN=("${AI[@]}")
    SEC=("${AS[@]}")
fi

kitty @ launch --cwd=$CWD --location=vsplit &>/dev/null && kitty @ send-text "${SEC[0]}\n"
kitty @ launch --cwd=$CWD --location=hsplit &>/dev/null && kitty @ send-text "${SEC[1]}\n"
kitty @ launch --cwd=$CWD --location=hsplit &>/dev/null && kitty @ send-text "${MAIN[1]}\n"
eval "${MAIN[0]}"
